# Generated by Django 6.0.2 on 2026-05-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_grant_teacher_learning_permissions'),
        ('webpush', '0005_auto_20230614_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('push_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_meta', to='webpush.pushinformation')),
            ],
        ),
    ]
