# Generated by Django 6.0.1 on 2026-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_choice_group_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='answers', to='learning.choice'),
        ),
    ]
