# Generated by Django 6.0.2 on 2026-02-13 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role_student_teacher'),
        ('learning', '0003_remove_answer_answer_text_answer_selected_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to='accounts.teacher'),
        ),
    ]
