# Generated by Django 6.0.2 on 2026-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_group_teaching_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
