# Generated by Django 6.0.2 on 2026-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_question_instruction_alter_answer_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
