# Generated by Django 6.0.2 on 2026-04-17

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_WORKBOOK_TITLE = "General"
DEFAULT_UNIT_TITLE = "General"


def assign_default_units(apps, schema_editor):
    Subject = apps.get_model("learning", "Subject")
    Workbook = apps.get_model("learning", "Workbook")
    Unit = apps.get_model("learning", "Unit")
    Topic = apps.get_model("learning", "Topic")

    for subject in Subject.objects.all().iterator():
        workbook, _ = Workbook.objects.get_or_create(
            subject_id=subject.id,
            title=DEFAULT_WORKBOOK_TITLE,
            defaults={
                "description": "Auto-created workbook for existing topics.",
            },
        )
        unit, _ = Unit.objects.get_or_create(
            workbook_id=workbook.id,
            title=DEFAULT_UNIT_TITLE,
            defaults={
                "description": "Auto-created unit for existing topics.",
            },
        )
        Topic.objects.filter(subject_id=subject.id, unit__isnull=True).update(
            unit_id=unit.id
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0010_question_instruction_alter_answer_answered_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workbooks",
                        to="learning.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject__name", "title"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="learning.workbook",
                    ),
                ),
            ],
            options={
                "ordering": ["workbook__subject__name", "workbook__title", "title"],
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="topics",
                to="learning.unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="workbook",
            constraint=models.UniqueConstraint(
                fields=("subject", "title"),
                name="uq_workbook_subject_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("workbook", "title"),
                name="uq_unit_workbook_title",
            ),
        ),
        migrations.RunPython(assign_default_units, noop_reverse),
        migrations.RemoveConstraint(
            model_name="topic",
            name="uq_topic_subject_title",
        ),
        migrations.AlterField(
            model_name="topic",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="topics",
                to="learning.unit",
            ),
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["unit__workbook__title", "unit__title", "title"]},
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("unit", "title"),
                name="uq_topic_unit_title",
            ),
        ),
    ]
