# Generated by Django 6.0.2 on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_role_teacher_topics"),
        ("learning", "0011_workbook_unit_topic_hierarchy"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupTopicSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_schedule_entries",
                        to="learning.group",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_topic_schedule_entries",
                        to="accounts.teacher",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_topic_schedule_entries",
                        to="learning.topic",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "scheduled_for",
                    "group__name",
                    "teacher__user__username",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="grouptopicschedule",
            constraint=models.UniqueConstraint(
                fields=("group", "teacher", "scheduled_for"),
                name="uq_group_teacher_topic_schedule_date",
            ),
        ),
        migrations.AddIndex(
            model_name="grouptopicschedule",
            index=models.Index(
                fields=["teacher", "scheduled_for"],
                name="learning_gr_teacher_d5bc61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grouptopicschedule",
            index=models.Index(
                fields=["group", "scheduled_for"],
                name="learning_gr_group_i_a2cc39_idx",
            ),
        ),
    ]
