# Generated by Django 6.0.2 on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0012_grouptopicschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="schedule_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="learning.grouptopicschedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(schedule_entry__isnull=False),
                fields=("student", "schedule_entry"),
                name="uq_attempt_student_schedule_entry",
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["schedule_entry"], name="learning_at_schedul_1beed6_idx"),
        ),
    ]
