# Generated by Django 6.0.2 on 2026-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_attempt_schedule_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
