# Generated by Django 6.0.2 on 2026-05-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0011_topic_src"),
        ("learning", "0013_attempt_schedule_entry"),
    ]

    operations = []
