# Generated by Django 6.0.2 on 2026-05-16 05:27

import django.db.models.deletion
from django.db import migrations, models


def migrate_topic_pools_to_tasks(apps, _schema_editor):
    Topic = apps.get_model("learning", "Topic")
    Task = apps.get_model("learning", "Task")
    Question = apps.get_model("learning", "Question")
    GroupTopicSchedule = apps.get_model("learning", "GroupTopicSchedule")
    GroupTeachingAssignment = apps.get_model("learning", "GroupTeachingAssignment")
    Attempt = apps.get_model("learning", "Attempt")

    task_by_topic_id = {}
    for topic in Topic.objects.all():
        task, _created = Task.objects.get_or_create(
            topic_id=topic.id,
            title="Default task",
            defaults={
                "description": topic.description,
                "is_active": topic.is_active,
                "src": topic.src,
            },
        )
        task_by_topic_id[topic.id] = task.id

    for topic_id, task_id in task_by_topic_id.items():
        Question.objects.filter(topic_id=topic_id, task__isnull=True).update(task_id=task_id)
        GroupTopicSchedule.objects.filter(topic_id=topic_id, task__isnull=True).update(task_id=task_id)
        GroupTeachingAssignment.objects.filter(topic_id=topic_id, task__isnull=True).update(task_id=task_id)
        Attempt.objects.filter(topic_id=topic_id, task__isnull=True).update(task_id=task_id)


def noop_reverse(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_teacher_topics'),
        ('learning', '0014_merge_topic_src_and_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('src', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['topic__unit__workbook__title', 'topic__unit__title', 'topic__title', 'title'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='grouptopicschedule',
            name='uq_group_teacher_topic_schedule_date',
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.topic'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='learning.task'),
        ),
        migrations.AddField(
            model_name='groupteachingassignment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='learning.task'),
        ),
        migrations.AddField(
            model_name='grouptopicschedule',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_topic_schedule_entries', to='learning.task'),
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.task'),
        ),
        migrations.RunPython(migrate_topic_pools_to_tasks, noop_reverse),
        migrations.AddConstraint(
            model_name='grouptopicschedule',
            constraint=models.UniqueConstraint(fields=('group', 'teacher', 'scheduled_for', 'task'), name='uq_group_teacher_task_schedule_date'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('topic', 'title'), name='uq_task_topic_title'),
        ),
    ]
