# Generated by Django 6.0.2 on 2026-05-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_add_is_success_to_attempt'),
        ('learning', '0015_task_and_more'),
    ]

    operations = [
    ]
