# Generated by Django 6.0.2 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0016_merge_20260517_1512"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="passing_correct_answers",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="task",
            name="questions_per_attempt",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
