# Generated by Django 6.0.2 on 2026-06-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_groupteachingassignment_workbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['unit__workbook__title', 'unit__title', 'title'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='workbook',
            options={'ordering': ['subject__name', 'title'], 'verbose_name': 'Textbook', 'verbose_name_plural': 'Textbooks'},
        ),
        migrations.AlterField(
            model_name='attempt',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='learning.topic', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='groupteachingassignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='learning.topic', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='groupteachingassignment',
            name='workbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='learning.workbook', verbose_name='textbook'),
        ),
        migrations.AlterField(
            model_name='grouptopicschedule',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_topic_schedule_entries', to='learning.topic', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.topic', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.topic', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='workbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='learning.workbook', verbose_name='textbook'),
        ),
    ]
