# Generated by Django 6.0.2 on 2026-08-31 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_alter_topic_options_alter_workbook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_matching_pairs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='matching_left_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='matching_right_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('matching', 'Matching')], default='multiple_choice', max_length=30),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_content', models.TextField()),
                ('right_content', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='learning.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
